pindown the version of github.com/openconfig/gnoi (#76)
Fix https://github.com/Azure/sonic-buildimage/issues/7268

- Why I did it
The error message below is occurred in building image.
```
gnmi_server/server.go:144:42: cannot use srv (type *Server) as type system.SystemServer in argument to system.RegisterSystemServer:
  *Server does not implement system.SystemServer (missing system.mustEmbedUnimplementedSystemServer method)
```

- How I did it
Lock the version of github.com/openconfig/gnoi to previous version.